# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dhavalptl'
      - name: Install packages
        run: yarn
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - name: Publish
        run: |
          git config --global user.email ${{secrets.G_EMAIL}}
          git config --global user.name ${{secrets.G_NAME}}
          yarn run lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.G_TOKEN}}
  
